[package]
name = "rlbotguilauncher"
version = "0.2.0"
edition = "2021"
description = "RLBotGui Launcher"
license-file = "LICENSE"
repository = "https://github.com/swz-git/guilauncher"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.7"
directories = "5.0.1"
env_logger = "0.10.0"
log = "0.4.20"
octocrab = "0.30.1"
reqwest = "0.11.20"
self-replace = "1.3.6"
tokio = { version = "1.32.0", features = ["full"] }
yansi = "1.0.0-rc.1"
zip = "0.6.6"
zip-extract = "0.1.2"

[build-dependencies]
winres = "0.1"
